package com.twitch.bot.dynamo_db_model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Message_Count_Rolling_Window")
public class MessagesCount {
    
    private String id;
    private Long messageCount;
    private String hourMinutesKey;
    private String channelName;

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="message_count")
    public Long getMessageCount() {
     return messageCount;
     }

     public void setMessageCount(Long messageCount) {
         this.messageCount = messageCount;
     }

     @DynamoDBAttribute(attributeName="hour_minutes_key")
     public String getHourMinutesKey() {
         return hourMinutesKey;
     }

     public void setHourMinutesKey(String hourMinutesKey) {
         this.hourMinutesKey = hourMinutesKey;
     }

    @DynamoDBAttribute(attributeName="channel_name")
    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
}
